"""Evaluate the model generated by train.py.

References:
* https://www.tensorflow.org/tutorials/keras/save_and_load
"""

import tensorflow as tf
import argparse

from models import generate

MODEL_PATH = './trained_models/generator.h5'
EVAL_DATA_PATH = './data/DIV2K_valid_HR'


def main(args):
    generator = tf.keras.models.load(args.model_path)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    parser.add_argument('--model_path', default=MODEL_PATH,
                        help='Location of saved generator model.')

    args = parser.parse_arguments()
    main(args)
